#!/usr/bin/env python3
"""Render and verify the publication-facing Lean theorem roster."""

from __future__ import annotations

import argparse
import json
import re
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
PROJECT = ROOT.parent
MAP_PATH = PROJECT / "paper" / "theorem-map.json"
PAPER_PATH = PROJECT / "paper" / "latex" / "gray_code_evolution.tex"
if not PAPER_PATH.exists():
    PAPER_PATH = PROJECT / "paper" / "gray_code_evolution.tex"
README_PATH = ROOT / "README.md"


def declaration_sources() -> str:
    return "\n".join(
        path.read_text(encoding="utf-8")
        for path in ROOT.rglob("*.lean")
        if ".lake" not in path.parts
    )


def render() -> str:
    claims = json.loads(MAP_PATH.read_text(encoding="utf-8"))
    paper = PAPER_PATH.read_text(encoding="utf-8")
    sources = declaration_sources()
    rows = []
    for claim in claims:
        label = claim["label"]
        if f"\\label{{{label}}}" not in paper:
            raise SystemExit(f"missing paper label: {label}")
        for name in claim["lean"]:
            pattern = rf"\b(?:theorem|def|noncomputable\s+def)\s+{re.escape(name)}\b"
            if re.search(pattern, sources) is None:
                raise SystemExit(f"missing Lean declaration: {name}")
        rows.append(
            f"| `{label}` | {claim['title']} | "
            + ", ".join(f"`{name}`" for name in claim["lean"])
            + " |"
        )

    return "\n".join(
        [
            "<!-- GENERATED by scripts/render_publication_readme.py; DO NOT EDIT. -->",
            "# Lean 4 verification",
            "",
            "This directory contains the kernel-checked proof accompanying",
            "*Hamilton Cycles in the Noncrossing Partition Refinement Graph*.",
            "The root module imports the complete classification theorem and its proof.",
            "",
            "## Main theorem",
            "",
            "```lean",
            "theorem NCRefinementGraph_fin_isHamiltonian_iff (n : ℕ) :",
            "    (NCRefinementGraph (Finset.univ : Finset (Fin n))).IsHamiltonian ↔",
            "      n = 0 ∨ n = 1 ∨ (Even n ∧ 4 <= n)",
            "```",
            "",
            "For the usual nondegenerate range `n >= 3`, this says exactly that the",
            "refinement graph has a Hamilton cycle if and only if `n` is even.",
            "All even `n >= 4` use one uniform Petersen Boolean-block construction.",
            "Odd `n >= 3` are excluded by a general",
            "bipartite-imbalance proof, not by enumeration.",
            "",
            "## Paper-to-kernel map",
            "",
            "| Paper label | Mathematical statement | Lean declarations |",
            "|---|---|---|",
            *rows,
            "",
            "## Verification",
            "",
            "The toolchain is pinned in `lean-toolchain`. A first build may take several",
            "minutes while Lean compiles the complete transitive proof dependency set.",
            "",
            "```powershell",
            "python ../scripts/verify_manuscript.py",
            "lake exe cache get",
            "lake build Hamilton.Infrastructure.HamiltonianClassification",
            "lake build Hamilton.HamiltonianCycles",
            "lake env lean Hamilton/HamiltonianCyclesTheoremMap.lean",
            "lake env lean --trust=0 Hamilton/HamiltonianCyclesAxiomAudit.lean",
            "python scripts/render_publication_readme.py --check",
            "```",
            "",
            "Use the pinned manifest directly; do not run `lake update`. On Windows,",
            "extract the package to a short path such as `C:\\\\gray-proof` so that",
            "Mathlib's longest source paths remain below the Win32 path limit.",
            "",
            "The expected axiom output for the five audited endpoints is exactly",
            "`[propext, Classical.choice, Quot.sound]`. These are Lean/Mathlib's standard",
            "logical quotient and classical-choice dependencies; there is no project",
            "axiom, `sorry`, `admit`, or `native_decide` in the publication closure.",
            "",
            "## Module guide",
            "",
            "- `PetersenMatchingCode`: bijective canonical-matching/mask coordinates.",
            "- `PetersenGrayCycle`: reflected Gray cycles inside each Boolean block.",
            "- `PetersenBlockTree`: chord deletion and parent-child refinement edges.",
            "- `PetersenPorts`: explicit joining diamonds and port keys.",
            "- `PetersenTreeSwitch`: generic cycle cutting and square switching.",
            "- `PetersenGlobalCycle`: well-founded simultaneous block-tree assembly.",
            "- `SignedDyckInvolution`: the signed count and odd-order obstruction.",
            "- `HamiltonianClassification`: the complete theorem for every `n`.",
            "",
        ]
    )


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    content = render()
    if args.check:
        current = README_PATH.read_text(encoding="utf-8") if README_PATH.exists() else ""
        if current != content:
            raise SystemExit("lean4/README.md is stale")
    else:
        README_PATH.write_text(content, encoding="utf-8", newline="\n")


if __name__ == "__main__":
    main()
